version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: zsn_mysql 
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
        - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root' # TODO: Change this
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'
    volumes:
      - ./data:/var/lib/mysql