version: '2'
services:
  mysql:
    container_name: zsn_mysql
    restart: always
    image: mysql:5.7
    ports:
        - "6033:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root' # TODO: Change this
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'
    volumes:
      - ./data:/var/lib/mysql
# volumes:
#   mysql-data: /data